### ISSUE TITLE
Toolbar Icons on Smaller smartphones

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#287]
Haven't looked at the docs for a while... Nice work with the settings. 👍 
What is the minimum targeted width (iPhoneSE/5 is 320px)? The icons overflow onto the documentation content area.
A simple fix would be to add a conditional css style like so (without affecting the current style too much):
```css
@media screen and (max-width: 343px) {
    #head .h-tools ul {
        width: 3.25em;
    }
}
```
Another minor issue on mobile phones is that the icons get shoved behind the side-menu when it is opened. Part of the gear icon is visible floating on the documentation content area. Possibly, to get around this, a `display:none;` could be added to `.h-tools > .main` and `.h-tools > .online`.

## Screenshot
![2018-05-26_091538](https://user-images.githubusercontent.com/3848219/40576639-d0b27662-60c7-11e8-8da9-a00350c60041.png)
